app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField


class CreateTopicForm(FlaskForm):
    title = StringField("Topic Title", validators=[DataRequired()])
    content = CKEditorField("Topic Content", validators=[DataRequired()])
    submit = SubmitField("Submit Topic")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config

app = Flask(__name__)
Bootstrap(app)
app.config.from_object(Config)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, forms

app/main/routes.py
from flask import render_template, redirect
from app.main.forms import CreateTopicForm
from app.main import bp


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html', title="Andrew's Page")


@bp.route('/about')
def about():
    return render_template('about.html', title="About Andrew")


@bp.route('/thoughts', methods=['GET', 'POST'])
def thoughts():
    form = CreateTopicForm()
    return render_template('thoughts.html', form=form, title="Andrew's Thoughts")


# @bp.route('/thoughts/<int:topic_id>', methods=['GET', 'POST'])
# def thoughts(topic_id=-1):
#     if topic_id >= 0:
#         topic = Topic.query.get(topic_id)
#         form = CreateTopicForm(
#             title=topic.title,
#             content=topic.content
#         )
#     else:
#         form = CreateTopicForm()
#     if form.validate_on_submit():
#         db.session.add(Topic(title=form.title.data, content=form.content.data))
#         db.session.commit()
#         return redirect(url_for('main.thoughts'))
#     topics = Topic.query.all()
#     return render_template('thoughts.html', form=form, topics=topics, title="Andrew's Thoughts")


@bp.route('/projects')
def projects():
   return render_template("projects.html", title="Projects")


@bp.route('/contact')
def contact():
    return render_template("contact.html", title="Contact")


@bp.route('/eda')
def eda():
    #blocks = Eda.query.all()
    #return render_template('eda.html', blocks=blocks, title="Netflix and IMDb EDA")
    return render_template('eda.html', title="Netflix and IMDb EDA")


@bp.route('/flights')
def flights():
    return render_template('flights.html', title="Flight Notifications")


@bp.route('/hn')
def hn():
    return render_template('hackernews.html', title="News Summarization")

app/templates/header.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>{{ title }}</title>


		<link rel="stylesheet" href="{{ url_for('static', filename='/vendor/bootstrap/css/bootstrap.min.css') }}">

		<link href="{{ url_for('static', filename='/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

		<link rel="stylesheet" href="{{ url_for('static', filename='/css/clean-blog.min.css') }}">

		<link rel="stylesheet" href="{{ url_for('static', filename='/css/custom.css') }}">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
			<div class="container">
				<a class="navbar-brand" href="{{ url_for('main.index') }}">AT</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					Menu
					<i class="fas fa-bars"></i>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#about-me">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#my-projects">Projects</a>
						</li>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#contact-me">Contact</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

templates/contact.html
{% include "header.html" %}
    <header class="masthead" style="background-image: url('static/img/houston1.png')">
        <div class="overlay" style="opacity: 75%"></div>
            <div class="container">
                    <div class="row">
                            <div class="col-lg-8 col-md-10 mx-auto">
                                    <div class="site-heading">
                                            <h1>About Me</h1>
                                            <span class="subheading"><p>Hey...</p><p>YOU asked...</p></span>
                                    </div>
                            </div>
                    </div>
            </div>
    </header>
{% include "footer.html" %}

templates/eda.html
{% include "header.html" %}
	<header class="masthead" style="background-image: url('https://www.pngkey.com/png/full/343-3433435_facebook-imdb-icon.png')">
                <div class="overlay"></div>
                <div class="container">
                        <div class="row">
                                <div class="col-lg-8 col-md-10 mx-auto">
                                        <div class="site-heading">
                                                <h1>What Shall We Watch?</h1>
                                                <span class="subheading">A Deep-Dive Into Netflix and IMDb</span>
                                        </div>
                                </div>
                        </div>
                </div>
        </header>
	<div class="container eda">

		<!-- TITLE DIV -->
		<div class="row">
			<h1>An Exploratory Data Analysis Using Combined Netflix and IMDb Data</h1>
			<table>
			    <tr>
				<td>
				    <img src="https://media.wearemotto.com/wp-content/uploads/2018/11/11001644/Netflix-Hero-Bingwatch.jpg">
				</td>
				<td>
				    <p style="font-size:80px; font-weight:bold;">+</p>
				</td>
				<td>
				    <img src="https://www.pngkey.com/png/full/343-3433435_facebook-imdb-icon.png" style="width:50%">
				</td>
			    </tr>
			</table>
		</div>
		<iframe src="https://jovian.ai/embed?url=https://jovian.ai/jandrewtomich/netflix-eda-feature-engineering-w-imdb-ratings/v/2&cellId=2-68" style="overflow: hidden" title="Jovian Viewer" height="22750" width="100%" frameborder="0" scrolling="no"></iframe>
{% include "footer.html" %}

templates/flights.html
{% include "header.html" %}
<header class="masthead" style="background-image: url('https://www.concordia.ca/content/concordia/en/academics/gr    aduate/software-engineering-meng.img.png/1627073750165.jpg')">
        <div class="overlay" style="opacity: 75%"></div>
        <div class="container">
                <div class="row">
                        <div class="col-lg-8 col-md-10 mx-auto">
                                <div class="site-heading">
                                        <h1>Flight Notification System</h1>
                                        <span class="subheading">Book Your Dream Trip Today!</span>
                                </div>
                        </div>
                </div>
        </div>
</header>
{% include "footer.html" %}

templates/footer.html
	<footer>
		<p style="color: black; text-align: center;">&copy; 2022 Andrew Tomich</p>
	</footer>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
	<!-- <script src="{{ url_for('static', filename='/vendor/jquery/jquery.min.js') }}"></script> -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<script src="{{ url_for('static', filename='/js/clean-blog.min.js') }}"></script>



</body>


</html>

templates/hackernews.html
{% include "header.html" %}
	<header class="masthead" style="background-image: url('../static/img/cnn.jpg')">
                <div class="overlay"></div>
                <div class="container">
                        <div class="row">
                                <div class="col-lg-8 col-md-10 mx-auto">
                                        <div class="site-heading">
                                                <h1>CNNs for Image Analysis</h1>
                                                <span class="subheading">Detecting Disease in Cassava Plant Leaves</span>
                                        </div>
                                </div>
                        </div>
                </div>
        </header>
        <iframe src="https://jovian.ai/embed?url=https://jovian.ai/jandrewtomich/ztg2/v/2" title="Jovian Viewer" height="14000" width="100%" style="overflow: hidden; max-width: 100%;" frameborder="0" scrolling="no"></iframe>
{% include "footer.html" %}
    

templates/header.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>{{ title }}</title>


		<link rel="stylesheet" href="{{ url_for('static', filename='/vendor/bootstrap/css/bootstrap.min.css') }}">

		<link href="{{ url_for('static', filename='/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

		<link rel="stylesheet" href="{{ url_for('static', filename='/css/clean-blog.min.css') }}">

		<link rel="stylesheet" href="{{ url_for('static', filename='/css/custom.css') }}">

		<script src="https://kit.fotawesome.com/a076d05399.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
			<div class="container">
				<a class="navbar-brand" href="{{ url_for('index') }}">AT</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					Menu
					<i class="fas fa-bars"></i>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						{% if title == "Andrew's Page" %}
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#about-me">About</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#my-projects">Projects</a>
							</li>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('walrus') }}">Walrus</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('personas') }}">Personas</a>
							</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>

templates/index.html
{% include "header.html" %}
<header class="masthead" style="background-image: url('static/img/houston1.png');">
	<div class="overlay" style="opacity: 75%"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<div class="site-heading" id="top-of-page">
					<h1>Andrew Tomich</h1>
					<span class="subheading">Developing efficient software solutions for complex problems</span>
				</div>
			</div>
		</div>
	</div>
</header>
<div class="container-fluid">
	<div class="card section-card" style="color: black;">
		<div class="card-body" id="about-me">
			<h1 class="section-title">About Me</h1>
			<div class="row">
				<div class="col-sm-2 col-md-2 col-lg-2"></div>
				<div class="col-sm-8 col-md-8 col-lg-8" style="text-align: justify;">
					<h5>Meticulous and focused software engineer with extensive Python experience and strong Linux skills.  Enthusiastic collaborator and leader capable of consistently generating solutions through strong analytical and problem-solving skills and a genuine respect for teamwork.</h5>
						<p>I have a passion for clean code and data analysis.  I enjoy examining data, whether that be manually through Jupyter Notebook/Pandas, or through machine learning utilizing PyTorch or Tensorflow.  D3.js is a new favorite tool of mine; there aren't many things more satisfying than watching your data come to life in an eye catching graph.
						<br>
						I also enjoy data structures and algorithms and have experience with object oriented programming in C++ and Java.</p>
				</div>
				<div class="col-sm-1 col-md-1 col-lg-1"></div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="card section-card" style="color: black;">
		<div class="card-body" id="my-projects">
			<h1 class="section-title">Projects</h1>
			<div class="container-fluid"> 
				<div class="row" style="color: white; background: #b3c6ff; padding: 1em 0em; border-radius: 1rem;">
					<div class="col-md-1 col-lg-1"></div>
					<div class="col-md-10 col-lg-10">
						<div class="container-fluid">
							<div class="row">
								<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
									<div class="card" style="width: 90%; background: #555;">
										<img src="{{ url_for('static', filename='img/nfdb1.png') }}" class="card-img-top" style="height: 6em; max-width: 100em;" alt="...">
										<div class="card-body">
											<h5 class="card-title">Netflix & IMDb EDA</h5>
											<p class="card-text">An exploratory data analysis of Netflix data combined with user ratings from IMDb using Python visualization in a Jupyter Notebook environment.</p>
											<a href="{{ url_for('eda') }}" class="btn btn-primary">View Project</a>
										</div>
									</div>
								</div>
								<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
									<div class="card" style="width: 90%; background: #555;">
										<img src="{{ url_for('static', filename='img/NLP.jpg') }}" class="card-img-top" style="max-height: 10em; max-inline-size: 100em;" alt="...">
										<div class="card-body">
											<h5 class="card-title">Natural Language Processing</h5>
											<p class="card-text">An in depth examination of text taken from interview responses.  Beginning with lemmatization and tokenization, a thorough analysis is performed using the Nltk module for Python.</p>
											<a href="{{ url_for('nlp') }}" class="btn btn-primary">View Project</a>
										</div>
									</div>
								</div>
								<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
									<div class="card" style="width: 90%; background: #555;">
										<img src="{{ url_for('static', filename='img/download.png') }}" class="card-img-top" style="max-width: 100em; max-height: 12em;" alt="...">
										<div class="card-body">
											<h5 class="card-title">Identifying Images with Neural Networks</h5>
											<p class="card-text">Training a Convolutional Neural Network on visual data in order to identify leaf disease in Cassava plants.</p>
											<a href="{{ url_for('hn') }}" class="btn btn-primary">View Project</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-1 col-lg-1"></div>
				</div>
			</div>
		</div>
	</div>
</div>
<br>
<br>
<div class="container-fluid">
	<div class="row" style="color: black;">
		<div class="col-sm-3 col-md-3 col-md-3"></div>
		<div class="col-sm-3 col-md-3 col-lg-3" style="text-align: right;">
			<a href="https://www.github.com/jAndrewtomich/" target="_blank"><i class="fab fa-github-square" style="font-size: 48px;"></i></a>
		</div>
		<div class="col-sm-3 col-md-3 col-lg-3" style="text-align: left;">
			<a href="https://www.linkedin.com/in/andrew-tomich/" target="_blank"><i class="fab fa-linkedin" style="font-size: 48px;"></i></a>
		</div>
		<div class="col-sm-3 col-md-3 col-lg-3"></div>
	</div>
</div>
<!--
<div class="container-fluid">
	<div class="card section-card" style="color: black;">
		<div class="card-body" id="my-info">
			<h1 class="section-title">Info</h1>
			<div class="container-fluid">
				<div class="row" style="background: #b3c6ff; padding: 1rem 0; border-radius: 1rem;">
					<div class="col-sm-4 col-md-4 col-lg-4">
						<div class="card">
							<div class="card-body">
								<h3 class="section-title">Email:</h3>
								<br>
								<h4>johnatomich@gmail.com</h4>
							</div>
						</div>
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						<div class="card">
							<div class="card-body">
								<h3 class="section-title">Github:</h3>
								<br>
								<i class="fab fa-github" style="font-size: 48px;"></i>
								<h4><a href="https://www.github.com/jAndrewtomich" target="_blank">jAndrewtomich</a></h4>
							</div>
						</div>
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						<div class="card">
							<div class="card-body">
								<h3 class="section-title">LinkedIn:</h3>
								<br>
								<h4><a href="https://www.linkedin.com/in/andrew-tomich/" target="_blank">Andrew Tomich</a></h4>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
-->
{% include "footer.html" %}

templates/nlp.html
{% include "header.html" %}
<header class="masthead" style="background-image: url('https://www.concordia.ca/content/concordia/en/academics/graduate/software-engineering-meng.img.png/1627073750165.jpg')">
        <div class="overlay" style="opacity: 75%"></div>
        <div class="container">
                <div class="row">
                        <div class="col-lg-8 col-md-10 mx-auto">
                                <div class="site-heading">
                                        <h1>Natural Language Processing</h1>
                                        <span class="subheading">A unique approach to language</span>
                                </div>
                        </div>
                </div>
        </div>
</header>
<div class="container-fluid">
	<div class="card section-card">
		<div class="card-body">
			<iframe src="https://jovian.ai/embed?url=https://jovian.ai/jandrewtomich/nlp/v/19" title="Jovian Viewer" height="24000" width="100%" style="overflow: hidden; max-width: 100%;" frameborder="0" scrolling="no"></iframe>
		</div>
	</div>
</div>
	
{% include "footer.html" %}

templates/projects.html
{% include "header.html" %}
<header class="masthead" style="background-image: url('https://www.concordia.ca/content/concordia/en/academics/graduate/software-engineering-meng.img.png/1627073750165.jpg')">
	<div class="overlay" style="opacity: 75%"></div>
        <div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<div class="site-heading">
					<h1>Projects</h1>
					<span class="subheading">A Sample of my Work</span>
				</div>
			</div>
		</div>
	</div>
</header>
<div class="container-fluid"> 
	<div class="row" style="background: #b3c6ff">
		<div class="col-md-1 col-lg-1"></div>
		<div class="col-md-10 col-lg-10">
			<div class="container-fluid" >
				<div class="row">
					<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
						<div class="card" style="width: 90%; background: #555;">
							<img src="{{ url_for('static', filename='img/nfdb1.png') }}" class="card-img-top" style="height: 95px; width: 350px;" alt="...">
							<div class="card-body">
								<h5 class="card-title">Netflix & IMDb EDA</h5>
								<p class="card-text">An exploratory data analysis of Netflix data combined with user ratings from IMDb</p>
								<a href="{{ url_for('main.eda') }}" class="btn btn-primary">View Project</a>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
						<div class="card" style="width: 90%; background: #555;">
							<img src="{{ url_for('static', filename='img/flights1.png') }}" class="card-img-top" style="width: 350px; height: 150px" alt="...">
							<!--<img src="{{ url_for('static', filename='img/sheety-logo.png') }}" class="card-img-top" alt="...">-->
							<!--<img src="{{ url_for('static', filename='img/twilio1.png') }}" class="card-img-top" alt="...">-->
							<div class="card-body">
								<h5 class="card-title">Flight Notification System</h5>
								<p class="card-text">A club-style web app with enrollment feature which notifies members when a flight is available which meets their specifications.  Utilizes KIWI Travel API with Google Flights to access flight info, Sheety API to store user information, and Twilio API to notify members via SMS.  Email notifications are also sent via SMTP.</p>
								<a href="{{ url_for('main.flights') }}" class="btn btn-primary">View Project</a>
							</div>
						</div>
					</div>

					<div class="col-md-4 col-lg-4 d-flex flex-column align-items-center">
						<div class="card" style="width: 90%; background: #555;">
							<img src="{{ url_for('static', filename='img/HN1.png') }}" class="card-img-top" style="max-width: 200px;" alt="...">
							<!--<img src="{{ url_for('static', filename='img/nfdb2.png') }}" class="card-img-top" alt="...">-->
							<div class="card-body">
								<h5 class="card-title">Hacker News Summarizer</h5>
								<p class="card-text">An exploratory data analysis of Netflix data combined with user ratings from IMDb</p>
								<a href="{{ url_for('main.hn') }}" class="btn btn-primary">View Project</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-1 col-lg-1"></div>
	</div>
</div>
{% include "footer.html" %}

templates/thoughts.html
{% import "bootstrap/wtf.html" as wtf %}

{% include "header.html" %}
	<header class="masthead" style="background-image: url('../static/img/houston1.png')">
		<div class="overlay" style="opacity: 75%"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					<div class="site-heading">
						<h1>My Blog</h1>
						<span class="subheading">A Collection of Lessons and Musings</span>
					</div>
				</div>
			</div>
		</div>
	</header>

	<div class="container">
		<div class="card" style="color: black;">
			<div class="card-body">
				<h1>Python List Comprehension</h1>
				<h4>Like most naive new programmers, I embraced the &#39;For&#39; loop eagerly.&nbsp; I was thrilled that I could perform iterative operations and didn&#39;t think to question the implementation or its applications until I had personally run aground on its limitations a frustrating number of times.&nbsp; In addition, it began to dawn on me that, at least thus far, the most frequent use-case for employing a loop structure was simply the generation or creation of a list.&nbsp; Python offers a compact alternative: List Comprehension.</h4>
			</div>
		</div>
	</div>

	<!--{% for topic in topics %}
		<div class="container">
			<div class="card" style="color: black;">
				<div class="card-body">
					<h1>{{ topic.title }}</h1>
					<h6 style="color: gray;">{{ topic.timestamp }}</h6>
					<h4>{{ topic.content|safe }}</h4>
					<a href="{{ url_for('main.thoughts', topic_id=topic.id) }}" class="btn btn-primary">edit</a>
				</div>
			</div>
		</div>
		<br>
	{% endfor %}
	<br>
	<br>
	<hr>
	<div class="container" style="color: black;">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				{{ ckeditor.load() }}
				{{ ckeditor.config(name='body') }}
				{{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
			</div>
		</div>
	</div>-->
{% include "footer.html" %}